### PR TITLE
Fix: Utilize SizedQueue in shard_reader, not consumer

### PR DESCRIPTION
**Pull request by odina**
Turns out we weren't making use of SizedQueue properly (my bad, I should have noticed this over code review, sorry).

Scenario:
kinesis' `get_records` call gets 10000 records at a time by default, we push this into the sized_queue as `[shard_id, array_of_10000_records]`

This means that how we were making use of SizedQueue technically wasn't ever going to solve the OOM issue since we'd probably run out of memory long before we reach the limit of 1000 (SQ limit) * 10000 (records) 🤦🏼

### CODE REVIEW

**Review by skolsuper — APPROVED** [review]
Oops 😅 

Is there a way to make the 10,000 configurable as a library option (rather than an env var).  Also the size of the SizedQueue.  I think Brain might need lower limits than Mailer or Engage because it doesn't hand off to sidekiq like they do.

**Review by wasabigeek — APPROVED** [review]
Sounds good, should we increase the SizedQueue or decrease the number in each get_records call (if that’s possible) as well?

(would be nice if we had a test)

**Comment by odina** [comment]
> Is there a way to make the 10,000 configurable as a library option (rather than an env var). Also the size of the SizedQueue. I think Brain might need lower limits than Mailer or Engage because it doesn't hand off to sidekiq like they do.

Got it. Will do so. Lifion-kinesis defaults to 10000 too, FTR.

**Comment by odina** [comment]
> Sounds good, should we increase the SizedQueue or decrease the number in each get_records call (if that’s possible) as well?

I think keeping get_records to 10000 seems reasonable, it's the default for AWS-SDK and lifion-kinesis. I'd much prefer to increase SizedQueue for the moment. Any recommendations for the size @skolsuper @wasabigeek ? 

> (would be nice if we had a test)

👌🏼

**Comment by skolsuper** [comment]
> > Sounds good, should we increase the SizedQueue or decrease the number in each get_records call (if that’s possible) as well?
> 
> I think keeping get_records to 10000 seems reasonable, it's the default for AWS-SDK and lifion-kinesis. I'd much prefer to increase SizedQueue for the moment. Any recommendations for the size @skolsuper @wasabigeek ?

I think reduce both.  The limit is a trade-off between memory and latency, and we have problems with memory not latency.  Getting OOM killed is actually disastrous tbh, we really ought to treat it very seriously.

**Comment by odina** [comment]
> I think Brain might need lower limits than Mailer or Engage because it doesn't hand off to sidekiq like they do.

Btw, for this one, since they all use the same stream, Brain will still need to get records fast, albeit discarding more records :(

**Comment by odina** [comment]
> I think reduce both. The limit is a trade-off between memory and latency, and we have problems with memory not latency. Getting OOM killed is actually disastrous tbh, we really ought to treat it very seriously.

Alright, in which case, will leave the configuration to the apps, and will default in kinesis-rb

**Comment by wasabigeek** [comment]
> Each data record can be up to [1 MiB](https://docs.aws.amazon.com/cli/latest/reference/kinesis/get-records.html#:~:text=Each%20data%20record%20can%20be%20up%20to%201%20MiB%20in%20size) in size

> The maximum size of data that GetRecords can return is [10 MiB](https://docs.aws.amazon.com/cli/latest/reference/kinesis/get-records.html#:~:text=The%20maximum%20size%20of%20data%20that%20GetRecords%20can%20return%20is%2010%20MiB). If a call returns this amount of data, subsequent calls made within the next 5 seconds throw ProvisionedThroughputExceededException

Doesn't sound too bad? (That second bit about rate limiting might be something to look out for in the future though)

**Comment by skolsuper** [comment]
> > Each data record can be up to [1 MiB](https://docs.aws.amazon.com/cli/latest/reference/kinesis/get-records.html#:~:text=Each%20data%20record%20can%20be%20up%20to%201%20MiB%20in%20size) in size
> 
> > The maximum size of data that GetRecords can return is [10 MiB](https://docs.aws.amazon.com/cli/latest/reference/kinesis/get-records.html#:~:text=The%20maximum%20size%20of%20data%20that%20GetRecords%20can%20return%20is%2010%20MiB). If a call returns this amount of data, subsequent calls made within the next 5 seconds throw ProvisionedThroughputExceededException
> 
> Doesn't sound too bad?

I think by default it waits 100ms between calls if the result is not empty?  So maximum 100MiB/s, will exhaust the memory pretty fast for our 512MB stream pollers, if the messages are big.

**Comment by skolsuper** [comment]
> > I think Brain might need lower limits than Mailer or Engage because it doesn't hand off to sidekiq like they do.
> 
> Btw, for this one, since they all use the same stream, Brain will still need to get records fast, albeit discarding more records :(

They don't need to go at the same rate;  each poller can read in its own time, without holding up anyone else.

**Comment by wasabigeek** [comment]
Quick check for my own understanding, I assume we don't have to do any special rollout, why? Is it something to do with the checkpointing + we restrict the no. of shard readers per shard? (Shooting in the dark here)

**Comment by skolsuper** [comment]
> Quick check for my own understanding, I assume we don't have to do any special rollout, why? Is it something to do with the checkpointing + we restrict the no. of shard readers per shard? (Shooting in the dark here)

There's one ShardReader per shard in each process.  IIRC when a process is starting a ShardReader, it takes out a lock in dynamoDB on that shard.  @odina can correct me if I'm wrong

**Pull request merged**
